version: 2

project_name: pomogoro

before:
  hooks:
    - go mod tidy
    - bash scripts/gen-icons.sh

builds:
  - id: darwin
    goos: [darwin]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w

  - id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

  - id: windows
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -H windowsgui

archives:
  - id: linux
    ids: [linux]
    formats: [tar.gz]
    files:
      - src: release/pomogoro.desktop
        dst: pomogoro.desktop
      - src: assets/stopwatch.svg
        dst: pomogoro.svg

  - id: windows
    ids: [windows]
    formats: [zip]

release:
  draft: true

checksum:
  name_template: checksums.txt

app_bundles:
  - id: darwin
    ids: [darwin]
    name: pomogoro
    bundle: dev.bemoty.pomogoro
    icon: assets/pomogoro.icns
    templated_extra_files:
      - src: release/Info.plist.tpl
        dst: Contents/Info.plist

dmg:
  - id: darwin-dmg
    ids: [darwin]
    name: "pomogoro-{{.Arch}}"
    use: appbundle
    replace: true

homebrew_casks:
  - name: pomogoro
    ids: [darwin-dmg]
    app: pomogoro.app
    repository:
      owner: bemoty
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://bemoty.dev
    description: Simple Pomodoro timer

msi:
  - id: windows-msi
    ids: [windows]
    name: "pomogoro-{{.MsiArch}}"
    wxs: windows/app.wxs
    extra_files:
      - assets/pomogoro.ico

scoops:
  - repository:
      owner: bemoty
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    ids: [windows]
    description: Simple Pomodoro timer
    homepage: https://bemoty.dev
    shortcuts:
      - ["pomogoro.exe", "pomogoro"]

aurs:
  - name: pomogoro-bin
    homepage: https://github.com/bemoty/pomogoro
    description: Simple Pomodoro timer
    maintainers: ["Joshua Winkler <josh@bemoty.dev>"]
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/pomogoro-bin.git
    ids: [linux]
    package: |
      install -Dm755 "./pomogoro" "${pkgdir}/usr/bin/pomogoro"
      install -Dm644 "./pomogoro.desktop" "${pkgdir}/usr/share/applications/pomogoro.desktop"
      install -Dm644 "./pomogoro.svg" "${pkgdir}/usr/share/icons/hicolor/scalable/apps/pomogoro.svg"
