version: 2

project_name: pomogoro

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    goos: [linux]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

  - id: windows
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -H windowsgui

archives:
  - id: linux
    ids: [linux]
    formats: [tar.gz]
    files:
      - src: release/pomogoro.desktop
        dst: pomogoro.desktop
      - src: assets/stopwatch.svg
        dst: pomogoro.svg

  - id: windows
    ids: [windows]
    formats: [zip]

release:
  draft: true

checksum:
  name_template: checksums.txt

scoops:
  - repository:
      owner: bemoty
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    ids: [windows]
    description: Simple Pomodoro timer
    homepage: https://bemoty.dev
    shortcuts:
      - ["pomogoro.exe", "pomogoro"]

aurs:
  - name: pomogoro-bin
    homepage: https://github.com/bemoty/pomogoro
    description: Simple Pomodoro timer
    maintainers: ["Joshua Winkler <josh@bemoty.dev>"]
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/pomogoro-bin.git
    ids: [linux]
    package: |
      install -Dm755 "./pomogoro" "${pkgdir}/usr/bin/pomogoro"
      install -Dm644 "./pomogoro.desktop" "${pkgdir}/usr/share/applications/pomogoro.desktop"
      install -Dm644 "./pomogoro.svg" "${pkgdir}/usr/share/icons/hicolor/scalable/apps/pomogoro.svg"
